input_boolean:
  residents:
    name: Residents
    initial: off
    icon: mdi:home-group

automation:
  - alias: "Update Residents Presence"
    trigger:
      - platform: state
        entity_id: device_tracker.person1
      - platform: state
        entity_id: device_tracker.person2
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.person1', 'home') and is_state('device_tracker.person2', 'home') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.residents
      - condition: else
      - service: input_boolean.turn_off
        entity_id: input_boolean.residents

